### ISSUE TITLE
Thanks for your effort

### ISSUE THREAD

**Issue by miketang84** [alexpdp7/retrofw2-rust#5]
I have LDK and plan to write a terminal (rewrite st-sdl) using Rust on it, found your work by searching, great appreciated on you.

+1

**Comment by alexpdp7** [comment]
Thanks!

You might want to check #developer-talk on the RetroFW 2 Discord, I normally check that out every couple of days and there's more knowledgeable people there (who helped me get this working).

As far as I know if you follow the README you should be able to compile things on the LDK. It takes a good amount of time (esp. compiling Buildroot). If you want, ping me and I can send you a binary so you can check it works on your device before starting to work on that.

If you feel instructions are not clear at some point or you need to make any change for the LDK, feel free to send a PR.

**Comment by miketang84** [comment]
Hi, I'm working on rust-sdl bindings in my spare time. Now do refactoring on it.

https://github.com/daogangtang/rust-sdl

**Comment by alexpdp7** [comment]
I think what might be interesting is to create an "SDL 1.2 driver" for a higher level graphics library or game engine. From what I see, while mixer/inputs are quite suitable for use, it's a bit of a pain to use the Rust bindings for graphics as it just provides very low-level primitives; if you want to draw vector graphics or any kind or render sprites I think you'll need a lot of code. If you could use any of the existing Rust libraries for that on SDL 1, that would be nicer.
